language: c
compiler: gcc
sudo: required

cache:
  directories:
    - ${HOME}/data

services:
  - docker

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

# https://stackoverflow.com/questions/23380369/defining-secure-environment-variables-for-multiple-repositories-in-a-single-tra
env:
  global:
    - secure: "Q4THr/vLJEQ2aAsJerrtpw4SIb5BhFZpMTu1lBe7Xningl3jRttOY1SxNkcKPtldwPMxR6o2QaVjOFEcqY9VLa07BUuAZ3NwNVdp/JkRV6+qb8vSRZcX9OWOkbBSIN5fHH09vDXUtcdA4ZyYAo5R9uCG1/+q8lLWOOZgPQHf8x4TtOkyv5sSUVu8oR4AWmYthc1b2ytsQ3jJE+NIH+J5VlEN3JtOEwbRyGdWVwTOVHn31umyXftI0P2PTJnHw/JTk875qcZ5T/aAsKAfkgX5Sg+/QVsxA7h9CXpKceH0CshZiJblokpPNdtWESn4ZzFxlxNFH/U/U8mwLepG6DsLEJdEntvzrZ6V6JlJkXDsKr6ohHqsiiq0KGlabhchlzCruW33PrE05Imyi+nCJ8FmChlKqiowtb1qztHXFxaL6rk3LbJtMyNHqVkih7/ofNHBo8owTbcv9Exq8E9WQjcURy5+Tw59OvO2ARrbqcGlIbwP/QjndgHpAYE7H4E5+vlEO+kPbdqsKo0pqNKaNg00aY5+kGYXx1gyYmxC4vTncW6sJMbSZd+jYbLi1ig+M4Nf5RpI98hNewK1gSqPDYe7bQPiIU2H1YTqeGpXb8ZL9rkYjv5AY583boTYT2VuVE8aiOaOQdCngrZe8URij9e3sr2VVJh3u62+gAZxRqchQHQ="
    - secure: "Vdp8dLbbm4chZ7Ym18eCqhs6zYAuq2UQB4xYgWCXtpbzxXCe7wR90HBkjdjKrxJnbtxCWCWxpHvyKJvG8uFemCJhwDqKxhiJfxPLCBvqe53qFWGKcx8c+dHSpzVuDC7JViO8fiFQ1ECbTl2yU9WRXps27F8q4U3vUOaG5Mj18fhdqpGuCMW1wr3YxddTbk4YCbYSfT1Vki9p7vy2YQxFcIZtO7YGytqGfTrEqVuXjPPk2XbGcmhgidoCwzMERAxUl2X8Nc5uqgUJDY6Xkmsxg8/OYrOjMdZRbyyD9ZsGEtBsj7gi51B/cjiC2DRdyGyOXlTL8+6nxzFr4PlC4BgXSqpHFg45thKGHp67n2ufsXt+P5B/iLJmstymiAH1ULrHiDUHKJiiYob1X86sjcipTYdQ9MH35ZKmLD9N6YWP+NCZzfA2OoWrf0uxg3TncqUJELOEPwflRz4mQ5hgBBq30CTplF0P1evnWXF3k4j1AqacaEipBy+lrWWGiwqtfwOR4KoSCqnav/Cc7rje896H0v4Mzm+RpoiY/VfmRfkvaTQViYKFpNom7/usB0kyZ80m/MPRhj4Vn5Z9y9tyF5mClyBCNuu/EBRgRBTlwyicHtMr0fR/YXXcRD68eXk5y/HPAqv9qOleBBtzhKcvxDG1ktP599ECsDIIH2Q1q1P2ZPo="

deploy:
  # https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

before_install:
  - docker build -t ${TRAVIS_REPO_SLUG,,}:${TRAVIS_CPU_ARCH} .

script:
  - docker run ${TRAVIS_REPO_SLUG,,}:${TRAVIS_CPU_ARCH} -h
