language: c
compiler: gcc
sudo: required

cache:
  directories:
    - ${HOME}/data

services:
  - docker

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

deploy:
  # https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

before_install:
  - docker build -t ${TRAVIS_REPO_SLUG,,}:${TRAVIS_CPU_ARCH} .

script:
  - docker run ${TRAVIS_REPO_SLUG,,}:${TRAVIS_CPU_ARCH} -h
